/*
 * This file is part of crash-reporter
 *
 * Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * Contact: Ville Ilvonen <ville.p.ilvonen@nokia.com>
 * Author: Riku Halonen <riku.halonen@nokia.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * version 2.1 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 *
 */

/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c CReporterNotificationAdaptor -a creporternotificationadaptor.h:creporternotificationadaptor.cpp com.nokia.CrashReporter.Notification.xml -N
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef CREPORTERNOTIFICATIONADAPTOR_H_1271742583
#define CREPORTERNOTIFICATIONADAPTOR_H_1271742583

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.nokia.CrashReporter.Notification
 */
class CReporterNotificationAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.nokia.CrashReporter.Notification")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.nokia.CrashReporter.Notification\">\n"
"    <!--\n"
"            Activates remote action in notification.\n"
"        -->\n"
"    <method name=\"activate\">\n"
"      <!-- arg type=\"av\" direction=\"in\"/ -->\n"
"    </method>\n"
"  </interface>\n"
        "")
public:
    CReporterNotificationAdaptor(QObject *parent);
    virtual ~CReporterNotificationAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void activate();
Q_SIGNALS: // SIGNALS
};

#endif
