/*
 * This file is part of crash-reporter
 *
 * Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * Contact: Ville Ilvonen <ville.p.ilvonen@nokia.com>
 * Author: Riku Halonen <riku.halonen@nokia.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License
 * version 2.1 as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
 * 02110-1301 USA
 *
 */

/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c CReporterDialogServerProxy -p creporterdialogserverproxy.h:creporterdialogserverproxy.cpp com.nokia.CrashReporter.DialogServer.xml -N
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef CREPORTERDIALOGSERVERPROXY_H_1271742962
#define CREPORTERDIALOGSERVERPROXY_H_1271742962

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

// HAND-EDIT
#include "creporterexport.h"
#include "creportermetatypes.h"

/*
 * Proxy class for interface com.nokia.CrashReporter.DialogServer
 */
class CREPORTER_EXPORT CReporterDialogServerProxy: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "com.nokia.CrashReporter.DialogServer"; }

public:
    CReporterDialogServerProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~CReporterDialogServerProxy();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<> quit()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("quit"), argumentList);
    }

    inline QDBusPendingReply<bool> requestDialog(const QString &dialogName, const QVariantList &arguments)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(dialogName) << qVariantFromValue(arguments);
        return asyncCallWithArgumentList(QLatin1String("requestDialog"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

#endif
