#!/bin/sh                               
#
# This file is part of crash-reporter
#
#  Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
#
#  Contact: Ville Ilvonen <ville.p.ilvonen@nokia.com>
#  Author: Riku Halonen <riku.halonen@nokia.com>
# 
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public License
#  version 2.1 as published by the Free Software Foundation.
# 
#  This program is distributed in the hope that it will be useful, but
#  WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public
#  License along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA
#  02110-1301 USA
#
#  

NAME=com.nokia.CrashReporter.Daemon 
OBJECT_PATH=/com/nokia/crashreporter/daemon 

# Get and export the address of user's D-Bus session bus
export DISPLAY=:0
source /tmp/session_bus_address.user

usage() {    
	echo "Script for requesting Crash Reporter to start or stop monitoring rich cores."
    echo "usage: $0 start | stop"
    exit
}

if [ -z "$1" ]; then
    usage
    exit
fi

case "$1" in
  start)
        echo "Starting monitoring..."
        qdbus $NAME $OBJECT_PATH com.nokia.CrashReporter.Daemon.startCoreMonitoring
	;;
  stop)
	echo "Stopping monitoring..."
        qdbus $NAME $OBJECT_PATH com.nokia.CrashReporter.Daemon.stopCoreMonitoring
	;;
  
  *)
      	;;
esac

exit 0
