#!/bin/sh

CORE_DIR=/var/cache/core-dumps
ENDURANCE_DIR=$CORE_DIR/endurance
SNAPSHOT_COUNT_FILE=$ENDURANCE_DIR/snapshot_count
BOOT_TIME_FILE=$ENDURANCE_DIR/boot_time
# BOOT_MARK_FILE should be on a filesystem that doesn't survive reboot.
BOOT_MARK_FILE=/tmp/endurance-collect-boot-mark
SNAPSHOTS_TO_PACK=12
MIN_SESSION_LENGTH=2

_print_header()
{
  printf '\n[---rich-core: %s---]\n' "$@"
}

_section_device_uid()
{
  _print_header device-uid
  ssu s | sed -n 's|Device UID: \([^\s]\+\)|\1|p'
}

_extract_btime()
{
  if [ -f "$1" ]; then
    cat $1 | grep btime | cut -d' ' -f 2
  fi
}

_section_boot_time()
{
  _print_header boot-time
  echo $boot_time
}

_section_endurance_snapshot_pack()
{
  _print_header endurance-snapshot-pack.tar.xz
  for snapshot in *; do
    if [ -d $snapshot ]; then
      SNAPSHOTS="$SNAPSHOTS $snapshot"
      for lzofile in $(ls $snapshot/*.lzo 2>/dev/null); do
        lzop -d $lzofile
        rm -f $lzofile
      done
    fi
  done

  tar c $SNAPSHOTS | xz -0 --stdout
}

_create_endurance_package()
{
  work_dir=$ENDURANCE_DIR.$(date +%s)
  mkdir "$work_dir"
  mv $ENDURANCE_DIR/??? "$work_dir"

  hwid=$(ssu-sysinfo -m)
  reportbasename=Endurance-${hwid}-$(date +%s)-${boot_time}

  (
    cd $work_dir
    _section_device_uid
    _section_boot_time
    _section_endurance_snapshot_pack
  ) | lzop > "${reportbasename}.tmp"

  rm -r $work_dir

  mv "${reportbasename}.tmp" "${reportbasename}.rcore.lzo"
}

cd $CORE_DIR

statfile=$(find $ENDURANCE_DIR -type f -name stat -print |head -n1)
boot_time=$(_extract_btime $statfile)

if [ -d "$ENDURANCE_DIR" ]; then
  snapshots_not_uploaded=$(ls -d1 $ENDURANCE_DIR/*/ | wc -l)
else
  snapshots_not_uploaded=0
fi

if [ -f "$BOOT_TIME_FILE" ]; then
  boot_time=$(cat "$BOOT_TIME_FILE")
else
  # Legacy code for smooth transition from older endurance-collect.
  statfile=$(find $ENDURANCE_DIR -type f -name stat -print |head -n1)
  boot_time=$(_extract_btime $statfile)
fi

if [ -f "$SNAPSHOT_COUNT_FILE" ]; then
  snapshots_in_session=$(cat "$SNAPSHOT_COUNT_FILE")
fi
if [ -z "$snapshots_in_session" ]; then
  snapshots_in_session=$snapshots_not_uploaded
fi

if [ ! -f "$BOOT_MARK_FILE" ]; then
  # After reboot, current session ends.
  if [ $snapshots_in_session -lt $MIN_SESSION_LENGTH ]; then
    # Too few snapshots were collected, discard the last session.
    rm -rf "$ENDURANCE_DIR"
  else
    # Package the remaining snapshots from previous session.
    _create_endurance_package
  fi

  # Initialize new session.
  mkdir -p "$ENDURANCE_DIR"
  snapshots_in_session=0
  touch "$BOOT_MARK_FILE"
  boot_time=$(_extract_btime /proc/stat)
  echo -n $boot_time > "$BOOT_TIME_FILE"
fi

/usr/bin/endurance-snapshot endurance
snapshots_not_uploaded=$(($snapshots_not_uploaded + 1))
snapshots_in_session=$(($snapshots_in_session + 1))
echo -n $snapshots_in_session > "$SNAPSHOT_COUNT_FILE"

if [ $snapshots_not_uploaded -ge $SNAPSHOTS_TO_PACK ]; then
  _create_endurance_package
fi
